repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/psf/black
  rev: 21.12b0
  hooks:
  - id: black
    language_version: python3.8
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort
    name: isort (python)
    args: ["--profile", "black"]
- repo: local
  hooks:
  - id: clean-nb
    name: clean notebooks
    description: clears outputs from all jupyter notebooks
    entry: scripts/clean_notebooks.sh
    language: system
    files: '.*\.ipynb'
  - id: update-deps
    name: update dependencies
    entry: scripts/update_deps.sh
    pass_filesnames: false
    language: system
    always_run: true
