learning_rate: 0.01
n_actions: 2
batch_size: 32
t_max: 1000
train_epochs: 50
env: CartPole-v0
env_name: cartpole
use_raw_env: true
target_delay: 1
delta: 0.001
multistep: 5
update_freq: 1
algo:
  - DDQN
  - Dueling
input_shape: [4]
qlearning_cfg:
  dense_layers:
    - 16
    - 16
callbacks:
  - type: InitBufferCallback
    kwargs:
      samples: 100
