use_raw_env: false
log_interval: 25
learning_rate: 0.001
minibatch_size: 50
batch_size: 64
t_max: 1000
train_epochs: 20000
max_buf_size: 40000
buf_size: 2000
multistep: 1
update_steps: 1
update_freq: 1
target_delay: 1
alpha: 1.0
beta: 1.0
epsilon: 0.1
delta: 0.0001
gamma: 0.99
algo:
  - "DDQN"
  - "Dueling"
qlearning_cfg:
  dense_layers:
    - 32
    - 32
callbacks:
  - type: "InitBufferCallback"
    kwargs:
      episodes: 100
