learning_rate: 0.0001
batch_size: 64
n_actions: 4
train_epochs: 20000
max_bu_size: 40000
env: gym_snake:snake-v0
env_name: snake
use_raw_env: false
multistep: 1
_multistep: 15
update_freq: 4
update_steps: 1
delta: 0.0001
lambda: 1.0
target_delay: 1
latent_dim: 16
algo:
  - DDQN
  - Dueling
  - SPR
callbacks:
  - type: InitBufferCallback
    kwargs:
      samples: 10000
  - type: AnnealingSchedulerCallback
    kwargs:
      target: epsilon
      schedule:
        - type: Schedule
          kwargs:
            length: 1000
            start_val: 0.4
            end_val: 0.1
            fn: linear
        - type: Schedule
          kwargs:
            length: 9000
            start_val: 0.1
            end_val: 0.01
            fn: linear
