learning_rate: 0.00005
n_actions: 4
n_frames: 1
train_epochs: 20000
env: "gym_snake:snake-v0"
env_name: "snake"
use_raw_env: false
multistep: 5
update_freq: 4
alpha: 0.6
beta: 0.4
delta: 0.00001
lambda: 0.00001
target_delay: 1
latent_dim: 16
log_interval: 25
algo:
  - DDQN
  - Dueling
callbacks:
  - type: InitBufferCallback
    kwargs:
      samples: 10000
  - type: AnnealingSchedulerCallback
    kwargs:
      target: epsilon
      schedule:
        - type: Schedule
          kwargs:
            length: 1000
            start_val: 0.4
            end_val: 0.1
            fn: linear
        - type: Schedule
          kwargs:
            length: 9000
            start_val: 0.1
            end_val: 0.01
            fn: linear
